disabled = false
languageCode = "ja"
languageName = "Japanese"
weight = 1
title = "技術的デジャブ回避メモ帳"

[params]
  displayName = "Ja"
  isoCode = "ja"
  rtl = false
  dateFormat = "2006年 1月 2日"
  description = "SESエンジニアの技術学習記録とトラブルシューティング備忘録。プログラミング、インフラ、開発環境の構築方法など実体験ベースで記録。"

 [params.author]
   name = "フミ"
   email = "ptin110825@gmail.com"
   image = "img/avater.png"
   imageQuality = 96
   headline = "2023年よりSES企業に勤務。RareTECH第55期生。<br> 自分の学習内容やエラー対応などをこのブログにまとめていきます。"
   links = [
     { link = "https://zenn.dev/mr110825"}, # Zennへのリンク
     { github = "https://github.com/mr110825" },
     { x-twitter = "https://x.com/mr110825" }
   ]
