disabled = false
languageCode = "ja"
languageName = "Japanese"
weight = 1
title = "技術的デジャブ回避メモ帳"

[params]
  displayName = "Ja"
  isoCode = "ja"
  rtl = false
  dateFormat = "2 January 2006"
  description = "技術的デジャブを回避するためにメモや備忘録"

 [params.author]
   name = "フミ"
   email = "ptin110825@gmail.com"
   image = "img/avater.png"
   imageQuality = 96
   headline = "学習内容や自分の失敗をアウトプットするためのブログです"
   links = [
     { link = "https://zenn.dev/mr110825"}, # Zennへのリンク
     { github = "https://github.com/mr110825" },
     { x-twitter = "https://x.com/mr110825" }
   ]
