[[main]]
  name = "Post"
  pageRef = "posts"
  weight = 10

#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20

#[[main]]
#  name = "Categories"
#  pageRef = "categories"
#  weight = 20

[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 20

